### ISSUE TITLE
Estructura básica del sitio

### ISSUE THREAD

**Issue by Alex-18030050** [paulvelizpractices/entorno_distribuido_paulveliz#1]
src >
        * index.html > "Estructura html del sitio"
        * css/
        * js/

**Comment by Alex-18030050** [comment]
Estructura basica del sitio realizada.

**Comment by pauvel** [comment]
@Alex-18030050  Me podrias decir porque no hay un PR para este Issue? quedo atento.

**Comment by pauvel** [comment]
Gracias, ya vi el PR #7 . Se cierra.
